### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by PercyDan54** [dnSpyEx/dnSpy#32]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
6.1.9
- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. delegate creation becomes like `<p0>, <p1>`
![image](https://user-images.githubusercontent.com/50285552/133958193-203f0db4-d8b4-48a6-a41c-00bd8137148c.png)
2. dnSpy resolves the wrong ctor:
![image](https://user-images.githubusercontent.com/50285552/133958254-caca47b5-8806-4802-923d-f9568568c330.png)
In this case there are 2 ctors, and one is using `string` which should be used.
![image](https://user-images.githubusercontent.com/50285552/133958297-ba3937fb-872f-4174-8187-bf5507c5eac3.png)

I guess this will be resolved with the update of ilspy lib?
The file: https://download.osufx.com/release/osu!.exe

**Comment by ElektroKill** [comment]
Hi, sorry for the rather late response. I had another look at your issue and I cannot reproduce point 2 with the latest release of dnSpyEx. Could you confirm that it also works for you? As for the reason why point 2 might no longer be an issue, it might be that the update to Roslyn 4.x has fixed this compiler issue.

As for point 1, I have pushed a fix for the invalid parameter names being generated. This was a bug that prevented the decompiler from removing the unnecessary parameter declarations. A build with the fix available can be found here https://github.com/dnSpyEx/dnSpy/actions/runs/2585026699 (at the time of writing this it is still building).

Could you please verify that both of the issues you outlined in the initial post are no longer present?

**Comment by PercyDan54** [comment]
I downloaded the build you linked and point 1 still exists
![image](https://user-images.githubusercontent.com/50285552/176659753-c368249e-3d6c-4191-9363-d30683fab60f.png)

**Comment by ElektroKill** [comment]
Hello, it seems my initial fix only fixed the problem for cases without nested delegate construction. Can you please try the build from https://github.com/dnSpyEx/dnSpy/actions/runs/2589578710 where I hopefully managed to fix this issue for nested delegate construction?

**Comment by PercyDan54** [comment]
> Hello, it seems my initial fix only fixed the problem for cases without nested delegate construction. Can you please try the build from https://github.com/dnSpyEx/dnSpy/actions/runs/2589578710 where I hopefully managed to fix this issue for nested delegate construction?

Can confrim it resolves it, thanks!
